// This file is auto-generated by the `update-kc-gen` command. Do not edit it manually.
// Hash: a9378e5b6031a6d6d53888e4541881291f9f2dda42c5e83c814aa499ded1883e


/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { lazy, Suspense, type ReactNode } from "react";

export type ThemeName = "phasetwo-ui";

export const themeNames: ThemeName[] = ["phasetwo-ui"];

export type KcEnvName = "SHOW_DARK_MODE_TOGGLE";

export const kcEnvNames: KcEnvName[] = ["SHOW_DARK_MODE_TOGGLE"];

export const kcEnvDefaults: Record<KcEnvName, string> = {
  "SHOW_DARK_MODE_TOGGLE": "false"
};

/**
 * NOTE: Do not import this type except maybe in your entrypoint. 
 * If you need to import the KcContext import it either from src/login/KcContext.ts or src/account/KcContext.ts.
 * Depending on the theme type you are working on.
 */
export type KcContext =
    | import("./login/KcContext").KcContext
    | import("./account/KcContext").KcContext
    | import("./admin/KcContext").KcContext
    ;

declare global {
    interface Window {
        kcContext?: KcContext;
    }
}

export const KcLoginPage = lazy(() => import("./login/KcPage"));
export const KcAccountPage = lazy(() => import("./account/KcPage"));
export const KcAdminPage = lazy(() => import("./admin/KcPage"));

export function KcPage(
    props: {
        kcContext: KcContext;
        fallback?: ReactNode;
    }
) {
    const { kcContext, fallback } = props;
    return (
        <Suspense fallback={fallback}>
            {(() => {
                switch (kcContext.themeType) {
                    case "login": return <KcLoginPage kcContext={kcContext} />;
                    case "account": return <KcAccountPage kcContext={kcContext} />;
                    case "admin": return <KcAdminPage kcContext={kcContext} />;
                }
            })()}
        </Suspense>
    );
}

// NOTE: This is exported here only because in Webpack environnement it works differently
export const BASE_URL = import.meta.env.BASE_URL

// NOTE: This is only exported here because you're supposed to import type from different packages
// Depending of if you are using Vite, Webpack, ect...
export type { Meta, StoryObj } from "@storybook/react-vite";
