# This file has been claimed for ownership from @keycloakify/email-native version 260007.0.0.
# To relinquish ownership and restore this file to its original content, run the following command:
# 
# $ npx keycloakify own --path "email/theme.properties" --revert

parent=mustache
locales=ar,ca,cs,da,de,el,en,es,fa,fr,fi,hu,it,ja,lt,nl,no,pl,pt,pt-BR,ru,sk,sv,th,tr,uk,zh-CN,zh-TW
